controllers:
    resource: ../src/Controller/
    type: annotation
    
kernel:
    resource: ../src/Kernel.php
    type: annotation

# home_page:
#     path: /
#     controller:  App\Controller\QuestionController::homepage

# blog_list:
#     path: /blog
#     # the controller value has the format 'controller_class::method_name'
#     controller: App\Controller\BlogController::list